language: php

php:
  - 5.6.37

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction --no-suggest

script: vendor/bin/phpunit -v

notifications:
    on_success: never
    on_failure: always
